### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by lonix1** [henkmollema/StartupModules#14]
Thanks for this very interesting library.

1. Does it work on net5?

2. I assume you have a "startup module" class for each major feature: one for logging, one for ioc container, one for security, one for EF, one for mvc / webapi, etc. How do you handle the situation where some middlewares need to be run in a certain order? e.g. static files first, or auth before mvc, etc.

**Comment by henkmollema** [comment]
Hi @lonix1, thanks for contacting me.

1.  Yes it works on .NET 5.
2. Correct. However I only use startup modules for middleware where the order doesn't matter that much. I still configure basic things such as static files and auth in the `Startup` class.
