### ISSUE TITLE
Another question

### ISSUE THREAD

**Issue by lonix1** [henkmollema/StartupModules#15]
Hey again @henkmollema, I've been using your code for a while and it's really useful, thanks again! :smile: 

One more question about your implementation if you don't mind?

`StartupModuleRunner` [has this](https://github.com/henkmollema/StartupModules/blob/master/src/StartupModules/StartupModuleRunner.cs#L47):
````cs
public void Configure(IApplicationBuilder app, IConfiguration configuration, IWebHostEnvironment hostingEnvironment)
{
    using var scope = app.ApplicationServices.CreateScope();     // <----------- ???
    var ctx = new ConfigureMiddlewareContext(configuration, hostingEnvironment, scope.ServiceProvider, _options);
    foreach (var cfg in _options.StartupModules)
    {
        cfg.Configure(app, ctx);
    }
}
````

You create a scope and use it to create a scoped container. That becomes available in a StartupModule's `Configure()` method.

Why?

This is [the signature](https://github.com/henkmollema/StartupModules/blob/master/src/StartupModules/StartupModule.cs#L24):
````cs
void Configure(IApplicationBuilder app, ConfigureMiddlewareContext context);
````

As you can see you could use `app.ApplicationServices` instead.

Can we simplify this code, or is there a reason for it I don't understand?

**Comment by lonix1** [comment]
I think I discovered the [answer here](https://stackoverflow.com/a/43066639/9971404). Thanks.

**Comment by henkmollema** [comment]
That's exactly the reason indeed.

Op do 1 jul. 2021 12:01 schreef lonix1 ***@***.***>:
