### ISSUE TITLE
Implement this in aspnet itself

### ISSUE THREAD

**Issue by lonix1** [henkmollema/StartupModules#16]
Henk I hope you don't mind but I [pointed](https://github.com/dotnet/aspnetcore/issues/33996) the aspnet guys to this repo. I wanted to inform you in case you have anything to add to that conversation.

I hope they can use it to implement something similar in the aspnet-core framework.

This code is incredibly useful. It would be nice to have it natively supported, maybe with even more features that we haven't thought of yet.

Thanks again!

**Comment by lonix1** [comment]
@henkmollema Looks like [they won't](https://github.com/dotnet/aspnetcore/issues/33996) introduce a modular startup idea into the framework itself.

So this library is "THE" way to do it. Thanks so much for making and maintaining it!

**Comment by henkmollema** [comment]
Glad you like it! I understand why they don't add this to the framework though. I needed this functionality myself and figured why not create a simple library for everyone. 😄
